server:
  port: 8081
  servlet:
    context-path: /ex

spring:
  security:
    user:
      name: root
      password: admin

management:
  server:
    port: 8090
    servlet:
      context-path: /sys
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'