server:
  port: 8081
  servlet:
    context-path: /ex

spring:
  rabbitmq:
    host: root
    password: admin
    virtual-host: /
    port: 5672
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual